// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/zerotrace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpanKind int32

const (
	SpanKind_SPAN_KIND_UNSPECIFIED SpanKind = 0
	SpanKind_SPAN_KIND_CLIENT      SpanKind = 1
	SpanKind_SPAN_KIND_SERVER      SpanKind = 2
)

// Enum value maps for SpanKind.
var (
	SpanKind_name = map[int32]string{
		0: "SPAN_KIND_UNSPECIFIED",
		1: "SPAN_KIND_CLIENT",
		2: "SPAN_KIND_SERVER",
	}
	SpanKind_value = map[string]int32{
		"SPAN_KIND_UNSPECIFIED": 0,
		"SPAN_KIND_CLIENT":      1,
		"SPAN_KIND_SERVER":      2,
	}
)

func (x SpanKind) Enum() *SpanKind {
	p := new(SpanKind)
	*p = x
	return p
}

func (x SpanKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_zerotrace_proto_enumTypes[0].Descriptor()
}

func (SpanKind) Type() protoreflect.EnumType {
	return &file_proto_zerotrace_proto_enumTypes[0]
}

func (x SpanKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanKind.Descriptor instead.
func (SpanKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_zerotrace_proto_rawDescGZIP(), []int{0}
}

type SpanBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Spans         []*Span                `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanBatch) Reset() {
	*x = SpanBatch{}
	mi := &file_proto_zerotrace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanBatch) ProtoMessage() {}

func (x *SpanBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerotrace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanBatch.ProtoReflect.Descriptor instead.
func (*SpanBatch) Descriptor() ([]byte, []int) {
	return file_proto_zerotrace_proto_rawDescGZIP(), []int{0}
}

func (x *SpanBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SpanBatch) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SpanBatch) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName string                 `protobuf:"bytes,5,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	StartTimeNs   int64                  `protobuf:"varint,6,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`
	EndTimeNs     int64                  `protobuf:"varint,7,opt,name=end_time_ns,json=endTimeNs,proto3" json:"end_time_ns,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Logs          []*SpanLog             `protobuf:"bytes,9,rep,name=logs,proto3" json:"logs,omitempty"`
	Kind          SpanKind               `protobuf:"varint,10,opt,name=kind,proto3,enum=zerotrace.v1.SpanKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_proto_zerotrace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerotrace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_proto_zerotrace_proto_rawDescGZIP(), []int{1}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Span) GetStartTimeNs() int64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *Span) GetEndTimeNs() int64 {
	if x != nil {
		return x.EndTimeNs
	}
	return 0
}

func (x *Span) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Span) GetLogs() []*SpanLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Span) GetKind() SpanKind {
	if x != nil {
		return x.Kind
	}
	return SpanKind_SPAN_KIND_UNSPECIFIED
}

type SpanLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanLog) Reset() {
	*x = SpanLog{}
	mi := &file_proto_zerotrace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanLog) ProtoMessage() {}

func (x *SpanLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerotrace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanLog.ProtoReflect.Descriptor instead.
func (*SpanLog) Descriptor() ([]byte, []int) {
	return file_proto_zerotrace_proto_rawDescGZIP(), []int{2}
}

func (x *SpanLog) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *SpanLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendSpansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *SpanBatch             `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSpansRequest) Reset() {
	*x = SendSpansRequest{}
	mi := &file_proto_zerotrace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSpansRequest) ProtoMessage() {}

func (x *SendSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerotrace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSpansRequest.ProtoReflect.Descriptor instead.
func (*SendSpansRequest) Descriptor() ([]byte, []int) {
	return file_proto_zerotrace_proto_rawDescGZIP(), []int{3}
}

func (x *SendSpansRequest) GetBatch() *SpanBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type SendSpansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSpansResponse) Reset() {
	*x = SendSpansResponse{}
	mi := &file_proto_zerotrace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSpansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSpansResponse) ProtoMessage() {}

func (x *SendSpansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerotrace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSpansResponse.ProtoReflect.Descriptor instead.
func (*SendSpansResponse) Descriptor() ([]byte, []int) {
	return file_proto_zerotrace_proto_rawDescGZIP(), []int{4}
}

func (x *SendSpansResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpansAccepted uint64                 `protobuf:"varint,1,opt,name=spans_accepted,json=spansAccepted,proto3" json:"spans_accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_zerotrace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zerotrace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_zerotrace_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetSpansAccepted() uint64 {
	if x != nil {
		return x.SpansAccepted
	}
	return 0
}

var File_proto_zerotrace_proto protoreflect.FileDescriptor

const file_proto_zerotrace_proto_rawDesc = "" +
	"\n" +
	"\x15proto/zerotrace.proto\x12\fzerotrace.v1\"d\n" +
	"\tSpanBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12(\n" +
	"\x05spans\x18\x03 \x03(\v2\x12.zerotrace.v1.SpanR\x05spans\"\xb0\x03\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12%\n" +
	"\x0eoperation_name\x18\x05 \x01(\tR\roperationName\x12\"\n" +
	"\rstart_time_ns\x18\x06 \x01(\x03R\vstartTimeNs\x12\x1e\n" +
	"\vend_time_ns\x18\a \x01(\x03R\tendTimeNs\x120\n" +
	"\x04tags\x18\b \x03(\v2\x1c.zerotrace.v1.Span.TagsEntryR\x04tags\x12)\n" +
	"\x04logs\x18\t \x03(\v2\x15.zerotrace.v1.SpanLogR\x04logs\x12*\n" +
	"\x04kind\x18\n" +
	" \x01(\x0e2\x16.zerotrace.v1.SpanKindR\x04kind\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\aSpanLog\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x10SendSpansRequest\x12-\n" +
	"\x05batch\x18\x01 \x01(\v2\x17.zerotrace.v1.SpanBatchR\x05batch\"/\n" +
	"\x11SendSpansResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\",\n" +
	"\x03Ack\x12%\n" +
	"\x0espans_accepted\x18\x01 \x01(\x04R\rspansAccepted*Q\n" +
	"\bSpanKind\x12\x19\n" +
	"\x15SPAN_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SPAN_KIND_CLIENT\x10\x01\x12\x14\n" +
	"\x10SPAN_KIND_SERVER\x10\x022\x9a\x01\n" +
	"\vTraceIngest\x12L\n" +
	"\tSendSpans\x12\x1e.zerotrace.v1.SendSpansRequest\x1a\x1f.zerotrace.v1.SendSpansResponse\x12=\n" +
	"\vStreamSpans\x12\x17.zerotrace.v1.SpanBatch\x1a\x11.zerotrace.v1.Ack(\x010\x01B,Z*github.com/zerotrace/zerotrace/proto;protob\x06proto3"

var (
	file_proto_zerotrace_proto_rawDescOnce sync.Once
	file_proto_zerotrace_proto_rawDescData []byte
)

func file_proto_zerotrace_proto_rawDescGZIP() []byte {
	file_proto_zerotrace_proto_rawDescOnce.Do(func() {
		file_proto_zerotrace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_zerotrace_proto_rawDesc), len(file_proto_zerotrace_proto_rawDesc)))
	})
	return file_proto_zerotrace_proto_rawDescData
}

var file_proto_zerotrace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_zerotrace_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_zerotrace_proto_goTypes = []any{
	(SpanKind)(0),             // 0: zerotrace.v1.SpanKind
	(*SpanBatch)(nil),         // 1: zerotrace.v1.SpanBatch
	(*Span)(nil),              // 2: zerotrace.v1.Span
	(*SpanLog)(nil),           // 3: zerotrace.v1.SpanLog
	(*SendSpansRequest)(nil),  // 4: zerotrace.v1.SendSpansRequest
	(*SendSpansResponse)(nil), // 5: zerotrace.v1.SendSpansResponse
	(*Ack)(nil),               // 6: zerotrace.v1.Ack
	nil,                       // 7: zerotrace.v1.Span.TagsEntry
}
var file_proto_zerotrace_proto_depIdxs = []int32{
	2, // 0: zerotrace.v1.SpanBatch.spans:type_name -> zerotrace.v1.Span
	7, // 1: zerotrace.v1.Span.tags:type_name -> zerotrace.v1.Span.TagsEntry
	3, // 2: zerotrace.v1.Span.logs:type_name -> zerotrace.v1.SpanLog
	0, // 3: zerotrace.v1.Span.kind:type_name -> zerotrace.v1.SpanKind
	1, // 4: zerotrace.v1.SendSpansRequest.batch:type_name -> zerotrace.v1.SpanBatch
	4, // 5: zerotrace.v1.TraceIngest.SendSpans:input_type -> zerotrace.v1.SendSpansRequest
	1, // 6: zerotrace.v1.TraceIngest.StreamSpans:input_type -> zerotrace.v1.SpanBatch
	5, // 7: zerotrace.v1.TraceIngest.SendSpans:output_type -> zerotrace.v1.SendSpansResponse
	6, // 8: zerotrace.v1.TraceIngest.StreamSpans:output_type -> zerotrace.v1.Ack
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_zerotrace_proto_init() }
func file_proto_zerotrace_proto_init() {
	if File_proto_zerotrace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_zerotrace_proto_rawDesc), len(file_proto_zerotrace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_zerotrace_proto_goTypes,
		DependencyIndexes: file_proto_zerotrace_proto_depIdxs,
		EnumInfos:         file_proto_zerotrace_proto_enumTypes,
		MessageInfos:      file_proto_zerotrace_proto_msgTypes,
	}.Build()
	File_proto_zerotrace_proto = out.File
	file_proto_zerotrace_proto_goTypes = nil
	file_proto_zerotrace_proto_depIdxs = nil
}
