// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/zerotrace.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TraceIngest_SendSpans_FullMethodName   = "/zerotrace.v1.TraceIngest/SendSpans"
	TraceIngest_StreamSpans_FullMethodName = "/zerotrace.v1.TraceIngest/StreamSpans"
)

// TraceIngestClient is the client API for TraceIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraceIngestClient interface {
	SendSpans(ctx context.Context, in *SendSpansRequest, opts ...grpc.CallOption) (*SendSpansResponse, error)
	StreamSpans(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SpanBatch, Ack], error)
}

type traceIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceIngestClient(cc grpc.ClientConnInterface) TraceIngestClient {
	return &traceIngestClient{cc}
}

func (c *traceIngestClient) SendSpans(ctx context.Context, in *SendSpansRequest, opts ...grpc.CallOption) (*SendSpansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSpansResponse)
	err := c.cc.Invoke(ctx, TraceIngest_SendSpans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traceIngestClient) StreamSpans(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SpanBatch, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TraceIngest_ServiceDesc.Streams[0], TraceIngest_StreamSpans_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SpanBatch, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TraceIngest_StreamSpansClient = grpc.BidiStreamingClient[SpanBatch, Ack]

// TraceIngestServer is the server API for TraceIngest service.
// All implementations must embed UnimplementedTraceIngestServer
// for forward compatibility.
type TraceIngestServer interface {
	SendSpans(context.Context, *SendSpansRequest) (*SendSpansResponse, error)
	StreamSpans(grpc.BidiStreamingServer[SpanBatch, Ack]) error
	mustEmbedUnimplementedTraceIngestServer()
}

// UnimplementedTraceIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTraceIngestServer struct{}

func (UnimplementedTraceIngestServer) SendSpans(context.Context, *SendSpansRequest) (*SendSpansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSpans not implemented")
}
func (UnimplementedTraceIngestServer) StreamSpans(grpc.BidiStreamingServer[SpanBatch, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamSpans not implemented")
}
func (UnimplementedTraceIngestServer) mustEmbedUnimplementedTraceIngestServer() {}
func (UnimplementedTraceIngestServer) testEmbeddedByValue()                     {}

// UnsafeTraceIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceIngestServer will
// result in compilation errors.
type UnsafeTraceIngestServer interface {
	mustEmbedUnimplementedTraceIngestServer()
}

func RegisterTraceIngestServer(s grpc.ServiceRegistrar, srv TraceIngestServer) {
	// If the following call panics, it indicates UnimplementedTraceIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TraceIngest_ServiceDesc, srv)
}

func _TraceIngest_SendSpans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSpansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceIngestServer).SendSpans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TraceIngest_SendSpans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceIngestServer).SendSpans(ctx, req.(*SendSpansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TraceIngest_StreamSpans_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraceIngestServer).StreamSpans(&grpc.GenericServerStream[SpanBatch, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TraceIngest_StreamSpansServer = grpc.BidiStreamingServer[SpanBatch, Ack]

// TraceIngest_ServiceDesc is the grpc.ServiceDesc for TraceIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraceIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zerotrace.v1.TraceIngest",
	HandlerType: (*TraceIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSpans",
			Handler:    _TraceIngest_SendSpans_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSpans",
			Handler:       _TraceIngest_StreamSpans_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/zerotrace.proto",
}
