// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadHttpTrace returns the embedded CollectionSpec for HttpTrace.
func LoadHttpTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HttpTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load HttpTrace: %w", err)
	}

	return spec, err
}

// LoadHttpTraceObjects loads HttpTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*HttpTraceObjects
//	*HttpTracePrograms
//	*HttpTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadHttpTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadHttpTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// HttpTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HttpTraceSpecs struct {
	HttpTraceProgramSpecs
	HttpTraceMapSpecs
}

// HttpTraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HttpTraceProgramSpecs struct {
	XdpPass *ebpf.ProgramSpec `ebpf:"xdp_pass"`
}

// HttpTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type HttpTraceMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// HttpTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadHttpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type HttpTraceObjects struct {
	HttpTracePrograms
	HttpTraceMaps
}

func (o *HttpTraceObjects) Close() error {
	return _HttpTraceClose(
		&o.HttpTracePrograms,
		&o.HttpTraceMaps,
	)
}

// HttpTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadHttpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type HttpTraceMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *HttpTraceMaps) Close() error {
	return _HttpTraceClose(
		m.Events,
	)
}

// HttpTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadHttpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type HttpTracePrograms struct {
	XdpPass *ebpf.Program `ebpf:"xdp_pass"`
}

func (p *HttpTracePrograms) Close() error {
	return _HttpTraceClose(
		p.XdpPass,
	)
}

func _HttpTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed httptrace_bpfeb.o
var _HttpTraceBytes []byte
