// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadSchedTrace returns the embedded CollectionSpec for SchedTrace.
func LoadSchedTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SchedTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SchedTrace: %w", err)
	}

	return spec, err
}

// LoadSchedTraceObjects loads SchedTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SchedTraceObjects
//	*SchedTracePrograms
//	*SchedTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSchedTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSchedTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SchedTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SchedTraceSpecs struct {
	SchedTraceProgramSpecs
	SchedTraceMapSpecs
}

// SchedTraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SchedTraceProgramSpecs struct {
	TracepointSchedProcessExec *ebpf.ProgramSpec `ebpf:"tracepoint__sched_process_exec"`
	TracepointSchedProcessExit *ebpf.ProgramSpec `ebpf:"tracepoint__sched_process_exit"`
}

// SchedTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SchedTraceMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// SchedTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSchedTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SchedTraceObjects struct {
	SchedTracePrograms
	SchedTraceMaps
}

func (o *SchedTraceObjects) Close() error {
	return _SchedTraceClose(
		&o.SchedTracePrograms,
		&o.SchedTraceMaps,
	)
}

// SchedTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSchedTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SchedTraceMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *SchedTraceMaps) Close() error {
	return _SchedTraceClose(
		m.Events,
	)
}

// SchedTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSchedTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SchedTracePrograms struct {
	TracepointSchedProcessExec *ebpf.Program `ebpf:"tracepoint__sched_process_exec"`
	TracepointSchedProcessExit *ebpf.Program `ebpf:"tracepoint__sched_process_exit"`
}

func (p *SchedTracePrograms) Close() error {
	return _SchedTraceClose(
		p.TracepointSchedProcessExec,
		p.TracepointSchedProcessExit,
	)
}

func _SchedTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed schedtrace_bpfel.o
var _SchedTraceBytes []byte
