// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SslTraceSslWriteArgsT struct {
	SslPtr uint64
	BufPtr uint64
	Num    uint32
	_      [4]byte
}

// LoadSslTrace returns the embedded CollectionSpec for SslTrace.
func LoadSslTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SslTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SslTrace: %w", err)
	}

	return spec, err
}

// LoadSslTraceObjects loads SslTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SslTraceObjects
//	*SslTracePrograms
//	*SslTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSslTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSslTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SslTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SslTraceSpecs struct {
	SslTraceProgramSpecs
	SslTraceMapSpecs
}

// SslTraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SslTraceProgramSpecs struct {
	UprobeSSL_read     *ebpf.ProgramSpec `ebpf:"uprobe__SSL_read"`
	UprobeSSL_write    *ebpf.ProgramSpec `ebpf:"uprobe__SSL_write"`
	UretprobeSSL_read  *ebpf.ProgramSpec `ebpf:"uretprobe__SSL_read"`
	UretprobeSSL_write *ebpf.ProgramSpec `ebpf:"uretprobe__SSL_write"`
}

// SslTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SslTraceMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	SslArgs *ebpf.MapSpec `ebpf:"ssl_args"`
}

// SslTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSslTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SslTraceObjects struct {
	SslTracePrograms
	SslTraceMaps
}

func (o *SslTraceObjects) Close() error {
	return _SslTraceClose(
		&o.SslTracePrograms,
		&o.SslTraceMaps,
	)
}

// SslTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSslTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SslTraceMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	SslArgs *ebpf.Map `ebpf:"ssl_args"`
}

func (m *SslTraceMaps) Close() error {
	return _SslTraceClose(
		m.Events,
		m.SslArgs,
	)
}

// SslTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSslTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type SslTracePrograms struct {
	UprobeSSL_read     *ebpf.Program `ebpf:"uprobe__SSL_read"`
	UprobeSSL_write    *ebpf.Program `ebpf:"uprobe__SSL_write"`
	UretprobeSSL_read  *ebpf.Program `ebpf:"uretprobe__SSL_read"`
	UretprobeSSL_write *ebpf.Program `ebpf:"uretprobe__SSL_write"`
}

func (p *SslTracePrograms) Close() error {
	return _SslTraceClose(
		p.UprobeSSL_read,
		p.UprobeSSL_write,
		p.UretprobeSSL_read,
		p.UretprobeSSL_write,
	)
}

func _SslTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ssltrace_bpfel.o
var _SslTraceBytes []byte
