// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTcpTrace returns the embedded CollectionSpec for TcpTrace.
func LoadTcpTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpTrace: %w", err)
	}

	return spec, err
}

// LoadTcpTraceObjects loads TcpTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpTraceObjects
//	*TcpTracePrograms
//	*TcpTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpTraceSpecs struct {
	TcpTraceProgramSpecs
	TcpTraceMapSpecs
}

// TcpTraceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpTraceProgramSpecs struct {
	KprobeTcpRecvmsg *ebpf.ProgramSpec `ebpf:"kprobe__tcp_recvmsg"`
	KprobeTcpSendmsg *ebpf.ProgramSpec `ebpf:"kprobe__tcp_sendmsg"`
}

// TcpTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpTraceMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// TcpTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpTraceObjects struct {
	TcpTracePrograms
	TcpTraceMaps
}

func (o *TcpTraceObjects) Close() error {
	return _TcpTraceClose(
		&o.TcpTracePrograms,
		&o.TcpTraceMaps,
	)
}

// TcpTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpTraceMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *TcpTraceMaps) Close() error {
	return _TcpTraceClose(
		m.Events,
	)
}

// TcpTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpTracePrograms struct {
	KprobeTcpRecvmsg *ebpf.Program `ebpf:"kprobe__tcp_recvmsg"`
	KprobeTcpSendmsg *ebpf.Program `ebpf:"kprobe__tcp_sendmsg"`
}

func (p *TcpTracePrograms) Close() error {
	return _TcpTraceClose(
		p.KprobeTcpRecvmsg,
		p.KprobeTcpSendmsg,
	)
}

func _TcpTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcptrace_bpfeb.o
var _TcpTraceBytes []byte
