// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadXdpClassifier returns the embedded CollectionSpec for XdpClassifier.
func LoadXdpClassifier() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpClassifierBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpClassifier: %w", err)
	}

	return spec, err
}

// LoadXdpClassifierObjects loads XdpClassifier and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpClassifierObjects
//	*XdpClassifierPrograms
//	*XdpClassifierMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpClassifierObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpClassifier()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpClassifierSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpClassifierSpecs struct {
	XdpClassifierProgramSpecs
	XdpClassifierMapSpecs
}

// XdpClassifierSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpClassifierProgramSpecs struct {
	XdpClassifier *ebpf.ProgramSpec `ebpf:"xdp_classifier"`
}

// XdpClassifierMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpClassifierMapSpecs struct {
}

// XdpClassifierObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpClassifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpClassifierObjects struct {
	XdpClassifierPrograms
	XdpClassifierMaps
}

func (o *XdpClassifierObjects) Close() error {
	return _XdpClassifierClose(
		&o.XdpClassifierPrograms,
		&o.XdpClassifierMaps,
	)
}

// XdpClassifierMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpClassifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpClassifierMaps struct {
}

func (m *XdpClassifierMaps) Close() error {
	return _XdpClassifierClose()
}

// XdpClassifierPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpClassifierObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpClassifierPrograms struct {
	XdpClassifier *ebpf.Program `ebpf:"xdp_classifier"`
}

func (p *XdpClassifierPrograms) Close() error {
	return _XdpClassifierClose(
		p.XdpClassifier,
	)
}

func _XdpClassifierClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpclassifier_bpfel.o
var _XdpClassifierBytes []byte
